title: UCL ARC Python tooling
description: Common Python tooling used in UCL's Advanced Research Computing center
theme: just-the-docs

url: https://UCL-ARC.github.io/python-tooling

color_scheme: dark

layouts_dir: _layouts

aux_links:
  Source repository: https://github.com/UCL-ARC/python-tooling
aux_links_new_tab: true

logo: "https://raw.githubusercontent.com/UCL-ARC/python-tooling/main/images/logo.svg"

plugins:
  - jekyll-gfm-admonitions
